"""JavaScript code generator with FFI support"""
from parser import *
from ffi import gen_ffi_js, ImportResolver

class JSCodeGen:
    def __init__(self, optimize: int = 1):
        self.optimize = optimize
        self.indent_level = 0
        self.output = []
        self.resolver = ImportResolver()

    def emit(self, code: str):
        indent = "  " * self.indent_level
        self.output.append(indent + code)

    def generate(self, program: Program) -> str:
        self.output = []
        self.emit("// Generated by Ketamine Compiler")
        self.emit("'use strict';")
        self.emit("")

        # Process imports first
        for imp in program.imports:
            warn = self.resolver.resolve(imp)
            if warn:
                self.emit(f"// {warn}")

        # Emit FFI preamble
        preamble = self.resolver.emit_js_preamble()
        if preamble:
            self.emit(preamble)
            self.emit("")

        # Runtime helpers
        self._emit_runtime()

        # Generate declarations
        for decl in program.declarations:
            self._visit(decl)

        # Call main if exists
        self.emit("")
        self.emit("// Entry point")
        self.emit("if (typeof main === 'function') {")
        self.indent_level += 1
        self.emit("const exitCode = main();")
        self.emit("process.exit(exitCode || 0);")
        self.indent_level -= 1
        self.emit("}")

        return "\n".join(self.output)
    
    def _emit_runtime(self):
        """Emit runtime library functions"""
        self.emit("// ── Ketamine Runtime ──────────────────────────────────────")
        self.emit("function print(val)   { console.log(String(val)); }")
        self.emit("function println(val) { console.log(String(val)); }")
        self.emit("function str(val)     { return String(val); }")
        self.emit("function panic(msg)   { throw new Error('[panic] ' + msg); }")
        self.emit("function sqrt(x)      { return Math.sqrt(x); }")
        self.emit("function abs(x)       { return Math.abs(x); }")
        self.emit("function min(a, b)    { return Math.min(a, b); }")
        self.emit("function max(a, b)    { return Math.max(a, b); }")
        self.emit("function clamp(v,lo,hi){ return Math.max(lo, Math.min(hi, v)); }")
        self.emit("// ── Bounds-checked array access ───────────────────────────")
        self.emit("function _idx(arr, i) {")
        self.indent_level += 1
        self.emit("if (i < 0 || i >= arr.length)")
        self.indent_level += 1
        self.emit("throw new Error(`Index ${i} out of bounds [0..${arr.length})`);")
        self.indent_level -= 2
        self.emit("  return arr[i]; }")
        self.emit("")
    
    def _visit(self, node: ASTNode):
        method = f'_gen_{node.__class__.__name__}'
        gen = getattr(self, method, self._generic)
        return gen(node)
    
    def _generic(self, node: ASTNode):
        return ""

    def _gen_ImportDecl(self, node):
        # Already handled in generate() — skip here
        return ""

    def _gen_NamespaceExpr(self, node: 'NamespaceExpr') -> str:
        """Emit FFI call or namespace path expression."""
        parts = node.parts
        if not parts:
            return "undefined"
        lang = parts[0] if parts[0] in ('python', 'c', 'rust', 'js', 'go') else None
        if lang:
            path = parts[1:]
            if lang == 'go':
                # Go is not directly callable from JS — emit a warning comment
                return f"/* go::{'.'.join(path)} — use --target go */"
            return gen_ffi_js(lang, path, [])   # args resolved at CallExpr level
        # Regular namespace — join with dots for now
        return ".".join(parts)
    
    def _gen_FnDecl(self, node: FnDecl):
        params = ", ".join(p.name for p in node.params)
        self.emit(f"function {node.name}({params}) {{")
        self.indent_level += 1
        
        if node.body:
            self._gen_Block(node.body)
        
        self.indent_level -= 1
        self.emit("}")
        self.emit("")
    
    def _gen_Block(self, node: Block):
        for stmt in node.stmts:
            self._visit(stmt)
    
    def _gen_VarDecl(self, node: VarDecl):
        keyword = "let" if node.is_mut else "const"
        if node.init:
            init = self._visit(node.init)
            self.emit(f"{keyword} {node.name} = {init};")
        else:
            self.emit(f"{keyword} {node.name};")
    
    def _gen_ReturnStmt(self, node: ReturnStmt):
        if node.value:
            val = self._visit(node.value)
            self.emit(f"return {val};")
        else:
            self.emit("return;")
    
    def _gen_IfStmt(self, node: IfStmt):
        cond = self._visit(node.cond)
        self.emit(f"if ({cond}) {{")
        self.indent_level += 1
        if node.then_branch:
            self._gen_Block(node.then_branch)
        self.indent_level -= 1
        
        if node.else_branch:
            self.emit("} else {")
            self.indent_level += 1
            self._gen_Block(node.else_branch)
            self.indent_level -= 1
        
        self.emit("}")
    
    def _gen_WhileStmt(self, node: WhileStmt):
        cond = self._visit(node.cond)
        self.emit(f"while ({cond}) {{")
        self.indent_level += 1
        if node.body:
            self._gen_Block(node.body)
        self.indent_level -= 1
        self.emit("}")
    
    def _gen_ForStmt(self, node: ForStmt):
        iter_expr = self._visit(node.iter)
        self.emit(f"for (const {node.var} of {iter_expr}) {{")
        self.indent_level += 1
        if node.body:
            self._gen_Block(node.body)
        self.indent_level -= 1
        self.emit("}")
    
    def _gen_ExprStmt(self, node: ExprStmt):
        expr = self._visit(node.expr)
        self.emit(f"{expr};")
    
    def _gen_BinaryExpr(self, node: BinaryExpr) -> str:
        left = self._visit(node.left)
        right = self._visit(node.right)
        op = node.op
        
        # Map operators
        op_map = {
            '&&': '&&', '||': '||',
            '==': '===', '!=': '!==',
        }
        op = op_map.get(op, op)
        
        return f"({left} {op} {right})"
    
    def _gen_UnaryExpr(self, node: UnaryExpr) -> str:
        operand = self._visit(node.operand)
        return f"({node.op}{operand})"
    
    def _gen_CallExpr(self, node: CallExpr) -> str:
        args = [self._visit(arg) for arg in node.args]

        # FFI namespace call: python::requests::get(url)
        if isinstance(node.callee, NamespaceExpr):
            parts = node.callee.parts
            lang  = parts[0] if parts[0] in ('python', 'c', 'rust', 'js') else None
            if lang:
                path = parts[1:]
                return gen_ffi_js(lang, path, args)
            # Non-FFI namespace — emit dotted call
            dotted = ".".join(parts)
            return f"{dotted}({', '.join(args)})"

        # Regular call
        callee = self._visit(node.callee)
        return f"{callee}({', '.join(args)})"
    
    def _gen_MemberExpr(self, node: MemberExpr) -> str:
        obj = self._visit(node.obj)
        return f"{obj}.{node.member}"
    
    def _gen_IndexExpr(self, node: IndexExpr) -> str:
        obj = self._visit(node.obj)
        idx = self._visit(node.index)
        # Bounds-checked access
        return f"_idx({obj}, {idx})"
    
    def _gen_AssignExpr(self, node: AssignExpr) -> str:
        target = self._visit(node.target)
        value = self._visit(node.value)
        return f"{target} = {value}"
    
    def _gen_Ident(self, node: Ident) -> str:
        return node.name
    
    def _gen_IntLiteral(self, node: IntLiteral) -> str:
        return str(node.value)
    
    def _gen_FloatLiteral(self, node: FloatLiteral) -> str:
        return str(node.value)
    
    def _gen_StringLiteral(self, node: StringLiteral) -> str:
        # Escape string
        escaped = node.value.replace('\\', '\\\\').replace('"', '\\"').replace('\n', '\\n')
        return f'"{escaped}"'
    
    def _gen_BoolLiteral(self, node: BoolLiteral) -> str:
        return "true" if node.value else "false"
