"""
Ketamine → Go code generator.
Produces idiomatic, compilable Go source from the Ketamine AST.
"""
from __future__ import annotations
from parser import (
    Program, FnDecl, VarDecl, StructDecl, EnumDecl, ImportDecl,
    Block, ReturnStmt, IfStmt, WhileStmt, ForStmt, ExprStmt,
    BinaryExpr, UnaryExpr, CallExpr, MemberExpr, IndexExpr,
    AssignExpr, NamespaceExpr, Ident,
    IntLiteral, FloatLiteral, StringLiteral, BoolLiteral,
    NullLiteral, ArrayLiteral, ASTNode,
)
from ffi import ImportResolver

# ─── Type mapping ─────────────────────────────────────────────────────────────

KET_TO_GO: dict[str, str] = {
    "int":   "int64",
    "float": "float64",
    "bool":  "bool",
    "str":   "string",
    "void":  "",
}

# Standard Go packages that map to go:: imports
GO_PKG_ALIASES: dict[str, str] = {
    "net":           "net",
    "net::http":     "net/http",
    "net::websocket":"golang.org/x/net/websocket",
    "fmt":           "fmt",
    "sync":          "sync",
    "time":          "time",
    "os":            "os",
    "bufio":         "bufio",
    "log":           "log",
    "math":          "math",
    "strings":       "strings",
    "strconv":       "strconv",
    "bytes":         "bytes",
    "io":            "io",
    "encoding::json":"encoding/json",
    "crypto::tls":   "crypto/tls",
    "crypto::rand":  "crypto/rand",
    "crypto::x509":  "crypto/x509",
    "context":       "context",
    "errors":        "errors",
}


def ket_type_to_go(t: str | None) -> str:
    if not t:
        return ""
    # Namespaced type: go::net::http::Request → *http.Request
    if "::" in t:
        parts = t.split("::")
        # Drop 'go' prefix if present
        if parts[0] == "go":
            parts = parts[1:]
        # Last part is the type name, second-to-last is the package alias
        if len(parts) >= 2:
            return f"*{parts[-2]}.{parts[-1]}"
        return parts[-1]
    return KET_TO_GO.get(t, t)


# ─── Code generator ───────────────────────────────────────────────────────────

class GoCodeGen:
    def __init__(self, optimize: int = 1, module_name: str = "ketamine_out"):
        self.optimize     = optimize
        self.module_name  = module_name
        self.resolver     = ImportResolver()

        self._lines:      list[str] = []
        self._indent:     int       = 0
        self._go_imports: set[str]  = set()
        self._go_imports.add("fmt")  # always needed for panic/print

    # ─── Emit helpers ─────────────────────────────────────────────────────────

    def _emit(self, line: str = ""):
        self._lines.append("    " * self._indent + line)

    def _indent_in(self):
        self._indent += 1

    def _indent_out(self):
        self._indent = max(0, self._indent - 1)

    def _need(self, pkg: str):
        self._go_imports.add(pkg)

    # ─── Entry point ──────────────────────────────────────────────────────────

    def generate(self, program: Program) -> str:
        # Collect imports
        for imp in program.imports:
            self.resolver.resolve(imp)
            if imp.lang == "go":
                raw = imp.module   # e.g. "net::http"
                go_pkg = GO_PKG_ALIASES.get(raw, raw.replace("::", "/"))
                self._need(go_pkg)

        # Body lines (generated before header so _go_imports is fully populated)
        body_gen = _BodyGen(self)
        body_lines: list[str] = []

        for decl in program.declarations:
            if isinstance(decl, ImportDecl):
                continue
            body_lines += body_gen.visit(decl)

        # Assemble final file
        out: list[str] = []
        out.append(f"// Generated by Ketamine Compiler — do not edit")
        out.append(f"package main")
        out.append("")

        if self._go_imports:
            out.append("import (")
            for pkg in sorted(self._go_imports):
                alias = _pkg_alias(pkg)
                if alias and alias != pkg.split("/")[-1]:
                    out.append(f'\t{alias} "{pkg}"')
                else:
                    out.append(f'\t"{pkg}"')
            out.append(")")
            out.append("")

        out += body_lines

        return "\n".join(out)


def _pkg_alias(pkg: str) -> str:
    """Return a short alias for a Go package path."""
    return pkg.split("/")[-1]


# ─── Body generator (visitor) ─────────────────────────────────────────────────

class _BodyGen:
    def __init__(self, cg: GoCodeGen):
        self.cg = cg

    def visit(self, node: ASTNode) -> list[str]:
        method = f"_visit_{node.__class__.__name__}"
        fn = getattr(self, method, self._visit_unknown)
        return fn(node)

    def _visit_unknown(self, node: ASTNode) -> list[str]:
        return [f"// TODO: {node.__class__.__name__}"]

    # ── Declarations ──────────────────────────────────────────────────────────

    def _visit_StructDecl(self, node: StructDecl) -> list[str]:
        lines = [f"type {node.name} struct {{"]
        for f in node.fields:
            go_type = ket_type_to_go(f.var_type)
            lines.append(f"\t{_capitalize(f.name)} {go_type}")
        lines.append("}")
        lines.append("")
        return lines

    def _visit_EnumDecl(self, node: EnumDecl) -> list[str]:
        lines = [f"type {node.name} int", ""]
        lines.append("const (")
        for i, v in enumerate(node.variants):
            if i == 0:
                lines.append(f"\t{node.name}_{v} {node.name} = iota")
            else:
                lines.append(f"\t{node.name}_{v}")
        lines.append(")")
        lines.append("")
        return lines

    def _visit_FnDecl(self, node: FnDecl) -> list[str]:
        lines: list[str] = []

        params = ", ".join(
            f"{p.name} {ket_type_to_go(p.var_type)}" for p in node.params
        )
        ret = ket_type_to_go(node.ret_type)

        if node.name == "main":
            # Entry point — wrap ketamine main
            lines.append("func main() {")
            lines.append("\t_ketamine_main()")
            lines.append("}")
            lines.append("")
            lines.append(f"func _ketamine_main() {'error' if ret else ''} {{")
        elif ret:
            lines.append(f"func {node.name}({params}) {ret} {{")
        else:
            lines.append(f"func {node.name}({params}) {{")

        if node.body:
            for stmt in node.body.stmts:
                for l in self._visit_stmt(stmt):
                    lines.append("\t" + l)

        lines.append("}")
        lines.append("")
        return lines

    # ── Statements ────────────────────────────────────────────────────────────

    def _visit_stmt(self, node: ASTNode) -> list[str]:
        method = f"_stmt_{node.__class__.__name__}"
        fn = getattr(self, method, self._stmt_expr)
        return fn(node)

    def _stmt_Block(self, node: Block) -> list[str]:
        lines = ["{"]
        for s in node.stmts:
            for l in self._visit_stmt(s):
                lines.append("\t" + l)
        lines.append("}")
        return lines

    def _stmt_VarDecl(self, node: VarDecl) -> list[str]:
        if node.init:
            expr = self._expr(node.init)
            if node.var_type:
                go_type = ket_type_to_go(node.var_type)
                return [f"var {node.name} {go_type} = {expr}"]
            return [f"{node.name} := {expr}"]
        go_type = ket_type_to_go(node.var_type or "int")
        return [f"var {node.name} {go_type}"]

    def _stmt_ReturnStmt(self, node: ReturnStmt) -> list[str]:
        if node.value:
            return [f"return {self._expr(node.value)}"]
        return ["return"]

    def _stmt_IfStmt(self, node: IfStmt) -> list[str]:
        cond = self._expr(node.cond)
        lines = [f"if {cond} {{"]
        if node.then_branch:
            for s in node.then_branch.stmts:
                for l in self._visit_stmt(s):
                    lines.append("\t" + l)
        if node.else_branch:
            lines.append("} else {")
            for s in node.else_branch.stmts:
                for l in self._visit_stmt(s):
                    lines.append("\t" + l)
        lines.append("}")
        return lines

    def _stmt_WhileStmt(self, node: WhileStmt) -> list[str]:
        cond = self._expr(node.cond)
        lines = [f"for {cond} {{"]
        if node.body:
            for s in node.body.stmts:
                for l in self._visit_stmt(s):
                    lines.append("\t" + l)
        lines.append("}")
        return lines

    def _stmt_ForStmt(self, node: ForStmt) -> list[str]:
        iterable = self._expr(node.iter)
        lines = [f"for _, {node.var} := range {iterable} {{"]
        if node.body:
            for s in node.body.stmts:
                for l in self._visit_stmt(s):
                    lines.append("\t" + l)
        lines.append("}")
        return lines

    def _stmt_ExprStmt(self, node: ExprStmt) -> list[str]:
        if node.expr:
            return [self._expr(node.expr)]
        return []

    def _stmt_expr(self, node: ASTNode) -> list[str]:
        return [self._expr(node)]

    # ── Expressions ───────────────────────────────────────────────────────────

    def _expr(self, node: ASTNode) -> str:
        method = f"_expr_{node.__class__.__name__}"
        fn = getattr(self, method, lambda n: f"/* {n.__class__.__name__} */")
        return fn(node)

    def _expr_IntLiteral(self, node: IntLiteral) -> str:
        return str(node.value)

    def _expr_FloatLiteral(self, node: FloatLiteral) -> str:
        s = str(node.value)
        return s if "." in s else s + ".0"

    def _expr_StringLiteral(self, node: StringLiteral) -> str:
        escaped = node.value.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n")
        return f'"{escaped}"'

    def _expr_BoolLiteral(self, node: BoolLiteral) -> str:
        return "true" if node.value else "false"

    def _expr_NullLiteral(self, _: NullLiteral) -> str:
        return "nil"

    def _expr_ArrayLiteral(self, node: ArrayLiteral) -> str:
        elems = ", ".join(self._expr(e) for e in node.elements)
        return f"[]interface{{}}{{{elems}}}"

    def _expr_Ident(self, node: Ident) -> str:
        return node.name

    def _expr_BinaryExpr(self, node: BinaryExpr) -> str:
        l = self._expr(node.left)
        r = self._expr(node.right)
        op_map = {"&&": "&&", "||": "||"}
        op = op_map.get(node.op, node.op)
        return f"({l} {op} {r})"

    def _expr_UnaryExpr(self, node: UnaryExpr) -> str:
        operand = self._expr(node.operand)
        op_map = {"!": "!", "-": "-"}
        return f"{op_map.get(node.op, node.op)}{operand}"

    def _expr_AssignExpr(self, node: AssignExpr) -> str:
        target = self._expr(node.target)
        value  = self._expr(node.value)
        return f"{target} = {value}"

    def _expr_MemberExpr(self, node: MemberExpr) -> str:
        obj = self._expr(node.obj)
        return f"{obj}.{_capitalize(node.member)}"

    def _expr_IndexExpr(self, node: IndexExpr) -> str:
        obj = self._expr(node.obj)
        idx = self._expr(node.index)
        return f"{obj}[{idx}]"

    def _expr_CallExpr(self, node: CallExpr) -> str:
        args = ", ".join(self._expr(a) for a in node.args)

        # FFI namespace call: go::net::http::ListenAndServe(...)
        if isinstance(node.callee, NamespaceExpr):
            return self._ffi_call(node.callee.parts, node.args)

        # Built-in rewrites
        if isinstance(node.callee, Ident):
            name = node.callee.name
            if name == "print" or name == "println":
                self.cg._need("fmt")
                return f"fmt.Println({args})"
            if name == "panic":
                self.cg._need("fmt")
                return f'func() {{ fmt.Println("panic:", {args}); panic({args}) }}()'
            if name == "str":
                self.cg._need("fmt")
                return f"fmt.Sprintf(\"%v\", {args})"
            if name == "sqrt":
                self.cg._need("math")
                return f"math.Sqrt({args})"

        callee = self._expr(node.callee)
        return f"{callee}({args})"

    def _expr_NamespaceExpr(self, node: NamespaceExpr) -> str:
        """Bare namespace (not called) — emit as value expression."""
        return self._ffi_path(node.parts)

    def _ffi_path(self, parts: list[str]) -> str:
        """Convert a :: path to Go dotted notation."""
        if parts and parts[0] in ("go",):
            parts = parts[1:]  # strip 'go' prefix
        if len(parts) == 0:
            return ""
        if len(parts) == 1:
            return parts[0]
        # e.g. ['net', 'http', 'ListenAndServe'] → http.ListenAndServe
        pkg   = parts[-2]
        ident = parts[-1]
        self.cg._need(_resolve_go_pkg(parts[:-1]))
        return f"{pkg}.{ident}"

    def _ffi_call(self, parts: list[str], raw_args: list) -> str:
        """Emit a Go FFI call from a NamespaceExpr + args."""
        if parts and parts[0] == "go":
            parts = parts[1:]

        args_str = ", ".join(self._expr(a) for a in raw_args)
        fn_expr  = self._ffi_path(["go"] + parts)  # re-adds go for path resolution

        # Special rewrites
        joined = "::".join(parts)
        if joined in _GO_BUILTIN_REWRITES:
            tmpl = _GO_BUILTIN_REWRITES[joined]
            pkg  = tmpl.split(".")[0]
            self.cg._need(_resolve_go_pkg(parts[:-1]))
            return f"{tmpl}({args_str})"

        return f"{fn_expr}({args_str})"


# ─── Go built-in rewrites ─────────────────────────────────────────────────────

_GO_BUILTIN_REWRITES: dict[str, str] = {
    # fmt
    "fmt::Println":   "fmt.Println",
    "fmt::Printf":    "fmt.Printf",
    "fmt::Sprintf":   "fmt.Sprintf",
    "fmt::Errorf":    "fmt.Errorf",
    # net/http
    "net::http::ListenAndServe":    "http.ListenAndServe",
    "net::http::ListenAndServeTLS": "http.ListenAndServeTLS",
    "net::http::NewServeMux":       "http.NewServeMux",
    "net::http::HandleFunc":        "http.HandleFunc",
    # net
    "net::Dial":     "net.Dial",
    "net::Listen":   "net.Listen",
    "net::ResolveTCPAddr": "net.ResolveTCPAddr",
    # sync
    "sync::WaitGroup": "sync.WaitGroup",
    "sync::Mutex":     "sync.Mutex",
    "sync::RWMutex":   "sync.RWMutex",
    # time
    "time::Sleep":   "time.Sleep",
    "time::Now":     "time.Now",
    "time::Second":  "time.Second",
    "time::Minute":  "time.Minute",
    # encoding/json
    "encoding::json::Marshal":   "json.Marshal",
    "encoding::json::Unmarshal": "json.Unmarshal",
    "encoding::json::NewEncoder":"json.NewEncoder",
    # crypto/tls
    "crypto::tls::Config":              "tls.Config",
    "crypto::tls::VersionTLS13":        "tls.VersionTLS13",
    "crypto::tls::LoadX509KeyPair":     "tls.LoadX509KeyPair",
    # os
    "os::Exit":     "os.Exit",
    "os::Getenv":   "os.Getenv",
    "os::Args":     "os.Args",
    # log
    "log::Println": "log.Println",
    "log::Fatal":   "log.Fatal",
    "log::Printf":  "log.Printf",
    # context
    "context::Background": "context.Background",
    "context::WithTimeout":"context.WithTimeout",
    # errors
    "errors::New":  "errors.New",
}


def _resolve_go_pkg(parts: list[str]) -> str:
    """Determine the full Go import path from a :: path."""
    if parts and parts[0] == "go":
        parts = parts[1:]
    key = "::".join(parts)
    return GO_PKG_ALIASES.get(key, "/".join(parts))


def _capitalize(s: str) -> str:
    """Capitalize first letter (Go exported names)."""
    return s[0].upper() + s[1:] if s else s
